version: 0.1

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "us-east-1"
    HUGO_VERSION: "0.19"
    HUGO_SHA256: "f5edfa4275a5011ea92e1a79dc9023f5d801f8ad52fcf05afabd1ce644dcf954"

phases:
  install:
    commands:
      - curl -Ls https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -o /tmp/hugo.tar.gz
      - echo "${HUGO_SHA256}  /tmp/hugo.tar.gz" | sha256sum -c -
      - tar xf /tmp/hugo.tar.gz -C /tmp
      - mv /tmp/hugo_${HUGO_VERSION}_linux_amd64/hugo_${HUGO_VERSION}_linux_amd64 /usr/bin/hugo
      - rm -rf /tmp/hugo*
  build:
    commands:
      - hugo
  post_build:
    commands:
      - aws configure set preview.cloudfront true
      - aws s3 sync --delete public s3://blog.rivernate.com --cache-control max-age=3600
      - aws cloudfront create-invalidation --distribution-id E2NJ1XSA5UXEGC --paths /index.html / /page/*