baseURL = "https://blog.rivernate.com/"
title = "Nathan Mills Blog"

theme = "beautifulhugo"
DefaultContentLanguage = "en"
pygmentsUseClasses = true
pygmentsCodeFences = true

#disqusShortname = "blog-rivernate-com"
googleAnalytics = "UA-93932964-1"
#copyright = "© Nathan Mills and rivernate.com, 2017. Unauthorized use and/or duplication of this material without express and written permission from this site’s author and/or owner is strictly prohibited. Excerpts and links may be used, provided that full and clear credit is given to Nathan Mills and rivernate.com with appropriate and specific direction to the original content."

[params]
  subtitle = "Nathan Mills's blog"
  useChroma = true
  rss = true

[Author]
  name = "Nathan Mills"
  website = "https://rivernate.com"
  #email = "nate@rivernate.com"
  github = "rivernate"
  twitter = "rivernate"
  linkedin = "nathan-mills"


[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3